name: Reset Allure History

on:
  workflow_dispatch:

jobs:
  delete-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4

      - name: Delete gh-pages branch via GitHub API
        run: |
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/gh-pages

      - name: Confirm deletion
        run: echo "gh-pages branch deleted. It will be recreated on next deploy."